NAME = PackageManager
NODENAME = tools

INCLUDES = $(ROOT)/$(NODENAME) $(ROOT)/tech/ThirdParty

include $(ROOT)/build/mk/common.vars.mk
include $(ROOT)/build/mk/fbx.mk
include $(ROOT)/build/mk/squish.mk
include $(ROOT)/build/mk/tbb.mk
include $(ROOT)/build/mk/lib.static.mk
