/****************************************************************************
This source file is (c) Teardrop Games LLC. All rights reserved. 
Redistribution and/or reproduction, in whole or in part, without prior
written permission of a duly authorized representative of Teardrop Games LLC
is prohibited.
****************************************************************************/

import "oaidl.idl";
import "ocidl.idl";

// // {D75EB882-8C58-4481-94A2-51DEA73DD78B}
//DEFINE_GUID(<<name>>, 0xd75eb882, 0x8c58, 0x4481, 0x94, 0xa2, 0x51, 0xde, 0xa7, 0x3d, 0xd7, 0x8b);


[
	object,
	uuid(D75EB882-8C58-4481-94A2-51DEA73DD78B),
	dual,
	helpstring("DCPExplorerExtension"),
	pointer_default(unique)
]
interface IDCPExplorerExtension : IDispatch
{
};

[
	uuid(A7182090-F4F0-47b0-939E-487A01A9FD95),
	version(1.0),
	helpstring("DCPExplorerExtension 1.0 Type Library")
]
library DCPExplorerExtensionLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(476193C7-9FDD-4e5b-AC0F-3296DEC42965),
		helpstring("DCPExplorerExtension Class")
	]
	coclass DCPExplorerExtension
	{
		[default] interface IDCPExplorerExtension;
	};
}