NAME = Package
INCLUDES = \
	$(ROOT)/tech/ThirdParty

SRCS = \
	platform/POSIX/UUIDStreamReader.cpp \
	platform/POSIX/UUIDStreamWriter.cpp

NODENAME = tech

include $(ROOT)/build/mk/common.vars.mk
include $(ROOT)/build/mk/lib.static.mk
