#include <wx/wxprec.h>
#include <wx/splitter.h>
#include <wx/treectrl.h>
#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/manager.h>
#include <wx/panel.h>
#include <wx/dialog.h>
#include <wx/listctrl.h>

// add additional headers here...
#include "Game/OrbitCamController.h"
#include "Game/FreeCamController.h"
#include "Game/TerrainPatch.h"
#include "Game/Scene.h"
#include "Game/SceneUtil.h"
#include "Game/Zone.h"
#include "Game/ZoneObject.h"
#include "Game/Component_Render.h"
#include "Game/Input.h"
#include "Game/InputFilter.h"
#include "Game/InputEvent.h"
#include "Game/ObjectLibrary.h"
#include "Game/Manifest.h"
#include "Game/LoadListener.h"
#include "Game/Component.h"
#include "Gfx/GfxRenderer.h"
#include "Gfx/GfxCamera.h"
#include "Gfx/GfxMaterial.h"
#include "Gfx/GfxMesh.h"
#include "Gfx/GfxSubMesh.h"
#include "Gfx/GfxTextureStage.h"
#include "Gfx/GfxTexture.h"
#include "Gfx/GfxRenderWindow.h"
#include "Gfx/GfxViewport.h"
#include "Physics/Physics.h"
#include "Animation/Animation.h"
#include "Resource/ResourceManager.h"
#include "Memory/Memory.h"
#include "Memory/MemoryRegion.h"
#include "Stream/FileStream.h"
#include "Reflection/Reflection.h"
#include "Reflection/ClassDef.h"
#include "Reflection/PropertyDef.h"
#include "Util/Logger.h"
#include "Util/Timer.h"
#include "Util/Environment.h"
#include "Util/_String.h"
#include "Util/StringUtil.h"
#include "Math/MathUtil.h"
#include "Math/Matrix44.h"
#include "Math/Transform.h"
#include "Math/Vector4.h"
#include "Math/Quaternion.h"

#include <string>
#include <list>
#include <map>
#include <algorithm>

#define DIRECTINPUT_VERSION 0x0800
#include <DInput.h>
