NAME = Util
SRCS = \
	platform/POSIX/FileSystem.cpp \
	platform/POSIX/UUID.cpp \
	platform/POSIX/Timer.cpp

NODENAME = tech

include $(ROOT)/build/mk/common.vars.mk
include $(ROOT)/build/mk/lib.static.mk
